namespace DO_AN_CUA_HAN.View
{
    partial class FormMainDeptMajor
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMainDeptMajor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonMajorAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox6 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonMajorEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox5 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonMajorDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonDeparmentAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonDepartmentEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDataGridViewMajor = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonDepartmentDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDataGridViewDeparment = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifubuttonMajorDeleteSearch = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBoxMajorSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewMajor)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewDeparment)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 30;
            this.bunifuShadowPanel1.BorderThickness = 0;
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonMajorAdd);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox6);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonMajorEdit);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox5);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonMajorDelete);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox4);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonDeparmentAdd);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonDepartmentEdit);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDataGridViewMajor);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonDepartmentDelete);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDataGridViewDeparment);
            this.bunifuShadowPanel1.Controls.Add(this.bunifubuttonMajorDeleteSearch);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBoxMajorSearch);
            this.bunifuShadowPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 0;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(940, 695);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 6;
            this.bunifuShadowPanel1.ControlAdded += new System.Windows.Forms.ControlEventHandler(this.bunifuShadowPanel1_ControlAdded);
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(795, 644);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(25, 32);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 25;
            this.pictureBox2.TabStop = false;
            // 
            // bunifuButtonMajorAdd
            // 
            this.bunifuButtonMajorAdd.AllowAnimations = true;
            this.bunifuButtonMajorAdd.AllowMouseEffects = true;
            this.bunifuButtonMajorAdd.AllowToggling = false;
            this.bunifuButtonMajorAdd.AnimationSpeed = 200;
            this.bunifuButtonMajorAdd.AutoGenerateColors = false;
            this.bunifuButtonMajorAdd.AutoRoundBorders = false;
            this.bunifuButtonMajorAdd.AutoSizeLeftIcon = true;
            this.bunifuButtonMajorAdd.AutoSizeRightIcon = true;
            this.bunifuButtonMajorAdd.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMajorAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMajorAdd.BackgroundImage")));
            this.bunifuButtonMajorAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.ButtonText = "        Thêm mới";
            this.bunifuButtonMajorAdd.ButtonTextMarginLeft = 0;
            this.bunifuButtonMajorAdd.ColorContrastOnClick = 45;
            this.bunifuButtonMajorAdd.ColorContrastOnHover = 45;
            this.bunifuButtonMajorAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonMajorAdd.CustomizableEdges = borderEdges1;
            this.bunifuButtonMajorAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMajorAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMajorAdd.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMajorAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMajorAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMajorAdd.IconMarginLeft = 11;
            this.bunifuButtonMajorAdd.IconPadding = 10;
            this.bunifuButtonMajorAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMajorAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMajorAdd.IconSize = 25;
            this.bunifuButtonMajorAdd.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonMajorAdd.IdleBorderRadius = 15;
            this.bunifuButtonMajorAdd.IdleBorderThickness = 1;
            this.bunifuButtonMajorAdd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorAdd.IdleIconLeftImage = null;
            this.bunifuButtonMajorAdd.IdleIconRightImage = null;
            this.bunifuButtonMajorAdd.IndicateFocus = false;
            this.bunifuButtonMajorAdd.Location = new System.Drawing.Point(788, 644);
            this.bunifuButtonMajorAdd.Name = "bunifuButtonMajorAdd";
            this.bunifuButtonMajorAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorAdd.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMajorAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorAdd.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMajorAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorAdd.onHoverState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.onHoverState.BorderThickness = 1;
            this.bunifuButtonMajorAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorAdd.onHoverState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.onHoverState.IconRightImage = null;
            this.bunifuButtonMajorAdd.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonMajorAdd.OnIdleState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMajorAdd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorAdd.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.OnIdleState.IconRightImage = null;
            this.bunifuButtonMajorAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorAdd.OnPressedState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMajorAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorAdd.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.OnPressedState.IconRightImage = null;
            this.bunifuButtonMajorAdd.Size = new System.Drawing.Size(115, 32);
            this.bunifuButtonMajorAdd.TabIndex = 24;
            this.bunifuButtonMajorAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMajorAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMajorAdd.TextMarginLeft = 0;
            this.bunifuButtonMajorAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMajorAdd.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox6
            // 
            this.pictureBox6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.pictureBox6.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox6.Image")));
            this.pictureBox6.Location = new System.Drawing.Point(654, 644);
            this.pictureBox6.Name = "pictureBox6";
            this.pictureBox6.Size = new System.Drawing.Size(25, 32);
            this.pictureBox6.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox6.TabIndex = 23;
            this.pictureBox6.TabStop = false;
            // 
            // bunifuButtonMajorEdit
            // 
            this.bunifuButtonMajorEdit.AllowAnimations = true;
            this.bunifuButtonMajorEdit.AllowMouseEffects = true;
            this.bunifuButtonMajorEdit.AllowToggling = false;
            this.bunifuButtonMajorEdit.AnimationSpeed = 200;
            this.bunifuButtonMajorEdit.AutoGenerateColors = false;
            this.bunifuButtonMajorEdit.AutoRoundBorders = false;
            this.bunifuButtonMajorEdit.AutoSizeLeftIcon = true;
            this.bunifuButtonMajorEdit.AutoSizeRightIcon = true;
            this.bunifuButtonMajorEdit.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMajorEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMajorEdit.BackgroundImage")));
            this.bunifuButtonMajorEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.ButtonText = "     Thay đổi";
            this.bunifuButtonMajorEdit.ButtonTextMarginLeft = 0;
            this.bunifuButtonMajorEdit.ColorContrastOnClick = 45;
            this.bunifuButtonMajorEdit.ColorContrastOnHover = 45;
            this.bunifuButtonMajorEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonMajorEdit.CustomizableEdges = borderEdges2;
            this.bunifuButtonMajorEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMajorEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMajorEdit.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMajorEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMajorEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMajorEdit.IconMarginLeft = 11;
            this.bunifuButtonMajorEdit.IconPadding = 10;
            this.bunifuButtonMajorEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMajorEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMajorEdit.IconSize = 25;
            this.bunifuButtonMajorEdit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonMajorEdit.IdleBorderRadius = 15;
            this.bunifuButtonMajorEdit.IdleBorderThickness = 1;
            this.bunifuButtonMajorEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorEdit.IdleIconLeftImage = null;
            this.bunifuButtonMajorEdit.IdleIconRightImage = null;
            this.bunifuButtonMajorEdit.IndicateFocus = false;
            this.bunifuButtonMajorEdit.Location = new System.Drawing.Point(647, 644);
            this.bunifuButtonMajorEdit.Name = "bunifuButtonMajorEdit";
            this.bunifuButtonMajorEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorEdit.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMajorEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorEdit.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMajorEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorEdit.onHoverState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.onHoverState.BorderThickness = 1;
            this.bunifuButtonMajorEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorEdit.onHoverState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.onHoverState.IconRightImage = null;
            this.bunifuButtonMajorEdit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonMajorEdit.OnIdleState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMajorEdit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorEdit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorEdit.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.OnIdleState.IconRightImage = null;
            this.bunifuButtonMajorEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorEdit.OnPressedState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMajorEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorEdit.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.OnPressedState.IconRightImage = null;
            this.bunifuButtonMajorEdit.Size = new System.Drawing.Size(115, 32);
            this.bunifuButtonMajorEdit.TabIndex = 22;
            this.bunifuButtonMajorEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMajorEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMajorEdit.TextMarginLeft = 0;
            this.bunifuButtonMajorEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMajorEdit.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox5
            // 
            this.pictureBox5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.pictureBox5.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox5.Image")));
            this.pictureBox5.Location = new System.Drawing.Point(512, 644);
            this.pictureBox5.Name = "pictureBox5";
            this.pictureBox5.Size = new System.Drawing.Size(25, 32);
            this.pictureBox5.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox5.TabIndex = 21;
            this.pictureBox5.TabStop = false;
            // 
            // bunifuButtonMajorDelete
            // 
            this.bunifuButtonMajorDelete.AllowAnimations = true;
            this.bunifuButtonMajorDelete.AllowMouseEffects = true;
            this.bunifuButtonMajorDelete.AllowToggling = false;
            this.bunifuButtonMajorDelete.AnimationSpeed = 200;
            this.bunifuButtonMajorDelete.AutoGenerateColors = false;
            this.bunifuButtonMajorDelete.AutoRoundBorders = false;
            this.bunifuButtonMajorDelete.AutoSizeLeftIcon = true;
            this.bunifuButtonMajorDelete.AutoSizeRightIcon = true;
            this.bunifuButtonMajorDelete.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMajorDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMajorDelete.BackgroundImage")));
            this.bunifuButtonMajorDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.ButtonText = "Xóa";
            this.bunifuButtonMajorDelete.ButtonTextMarginLeft = 0;
            this.bunifuButtonMajorDelete.ColorContrastOnClick = 45;
            this.bunifuButtonMajorDelete.ColorContrastOnHover = 45;
            this.bunifuButtonMajorDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonMajorDelete.CustomizableEdges = borderEdges3;
            this.bunifuButtonMajorDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMajorDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMajorDelete.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMajorDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMajorDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMajorDelete.IconMarginLeft = 11;
            this.bunifuButtonMajorDelete.IconPadding = 10;
            this.bunifuButtonMajorDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMajorDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMajorDelete.IconSize = 25;
            this.bunifuButtonMajorDelete.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonMajorDelete.IdleBorderRadius = 15;
            this.bunifuButtonMajorDelete.IdleBorderThickness = 1;
            this.bunifuButtonMajorDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorDelete.IdleIconLeftImage = null;
            this.bunifuButtonMajorDelete.IdleIconRightImage = null;
            this.bunifuButtonMajorDelete.IndicateFocus = false;
            this.bunifuButtonMajorDelete.Location = new System.Drawing.Point(505, 644);
            this.bunifuButtonMajorDelete.Name = "bunifuButtonMajorDelete";
            this.bunifuButtonMajorDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorDelete.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonMajorDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorDelete.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMajorDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorDelete.onHoverState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.onHoverState.BorderThickness = 1;
            this.bunifuButtonMajorDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorDelete.onHoverState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.onHoverState.IconRightImage = null;
            this.bunifuButtonMajorDelete.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonMajorDelete.OnIdleState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.OnIdleState.BorderThickness = 1;
            this.bunifuButtonMajorDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonMajorDelete.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorDelete.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.OnIdleState.IconRightImage = null;
            this.bunifuButtonMajorDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorDelete.OnPressedState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.OnPressedState.BorderThickness = 1;
            this.bunifuButtonMajorDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorDelete.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.OnPressedState.IconRightImage = null;
            this.bunifuButtonMajorDelete.Size = new System.Drawing.Size(115, 32);
            this.bunifuButtonMajorDelete.TabIndex = 20;
            this.bunifuButtonMajorDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMajorDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMajorDelete.TextMarginLeft = 0;
            this.bunifuButtonMajorDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMajorDelete.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox4
            // 
            this.pictureBox4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.pictureBox4.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox4.Image")));
            this.pictureBox4.Location = new System.Drawing.Point(330, 644);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(25, 32);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox4.TabIndex = 19;
            this.pictureBox4.TabStop = false;
            // 
            // bunifuButtonDeparmentAdd
            // 
            this.bunifuButtonDeparmentAdd.AllowAnimations = true;
            this.bunifuButtonDeparmentAdd.AllowMouseEffects = true;
            this.bunifuButtonDeparmentAdd.AllowToggling = false;
            this.bunifuButtonDeparmentAdd.AnimationSpeed = 200;
            this.bunifuButtonDeparmentAdd.AutoGenerateColors = false;
            this.bunifuButtonDeparmentAdd.AutoRoundBorders = false;
            this.bunifuButtonDeparmentAdd.AutoSizeLeftIcon = true;
            this.bunifuButtonDeparmentAdd.AutoSizeRightIcon = true;
            this.bunifuButtonDeparmentAdd.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDeparmentAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDeparmentAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDeparmentAdd.BackgroundImage")));
            this.bunifuButtonDeparmentAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDeparmentAdd.ButtonText = "        Thêm mới";
            this.bunifuButtonDeparmentAdd.ButtonTextMarginLeft = 0;
            this.bunifuButtonDeparmentAdd.ColorContrastOnClick = 45;
            this.bunifuButtonDeparmentAdd.ColorContrastOnHover = 45;
            this.bunifuButtonDeparmentAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButtonDeparmentAdd.CustomizableEdges = borderEdges4;
            this.bunifuButtonDeparmentAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDeparmentAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDeparmentAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDeparmentAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDeparmentAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonDeparmentAdd.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonDeparmentAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDeparmentAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDeparmentAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDeparmentAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonDeparmentAdd.IconMarginLeft = 11;
            this.bunifuButtonDeparmentAdd.IconPadding = 10;
            this.bunifuButtonDeparmentAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDeparmentAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDeparmentAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonDeparmentAdd.IconSize = 25;
            this.bunifuButtonDeparmentAdd.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonDeparmentAdd.IdleBorderRadius = 15;
            this.bunifuButtonDeparmentAdd.IdleBorderThickness = 1;
            this.bunifuButtonDeparmentAdd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDeparmentAdd.IdleIconLeftImage = null;
            this.bunifuButtonDeparmentAdd.IdleIconRightImage = null;
            this.bunifuButtonDeparmentAdd.IndicateFocus = false;
            this.bunifuButtonDeparmentAdd.Location = new System.Drawing.Point(325, 644);
            this.bunifuButtonDeparmentAdd.Name = "bunifuButtonDeparmentAdd";
            this.bunifuButtonDeparmentAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDeparmentAdd.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonDeparmentAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDeparmentAdd.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonDeparmentAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDeparmentAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDeparmentAdd.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDeparmentAdd.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDeparmentAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDeparmentAdd.onHoverState.BorderRadius = 15;
            this.bunifuButtonDeparmentAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDeparmentAdd.onHoverState.BorderThickness = 1;
            this.bunifuButtonDeparmentAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDeparmentAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDeparmentAdd.onHoverState.IconLeftImage = null;
            this.bunifuButtonDeparmentAdd.onHoverState.IconRightImage = null;
            this.bunifuButtonDeparmentAdd.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonDeparmentAdd.OnIdleState.BorderRadius = 15;
            this.bunifuButtonDeparmentAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDeparmentAdd.OnIdleState.BorderThickness = 1;
            this.bunifuButtonDeparmentAdd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDeparmentAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDeparmentAdd.OnIdleState.IconLeftImage = null;
            this.bunifuButtonDeparmentAdd.OnIdleState.IconRightImage = null;
            this.bunifuButtonDeparmentAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDeparmentAdd.OnPressedState.BorderRadius = 15;
            this.bunifuButtonDeparmentAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDeparmentAdd.OnPressedState.BorderThickness = 1;
            this.bunifuButtonDeparmentAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDeparmentAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDeparmentAdd.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDeparmentAdd.OnPressedState.IconRightImage = null;
            this.bunifuButtonDeparmentAdd.Size = new System.Drawing.Size(115, 32);
            this.bunifuButtonDeparmentAdd.TabIndex = 18;
            this.bunifuButtonDeparmentAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonDeparmentAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDeparmentAdd.TextMarginLeft = 0;
            this.bunifuButtonDeparmentAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDeparmentAdd.UseDefaultRadiusAndThickness = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(201, 644);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(25, 32);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 17;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuButtonDepartmentEdit
            // 
            this.bunifuButtonDepartmentEdit.AllowAnimations = true;
            this.bunifuButtonDepartmentEdit.AllowMouseEffects = true;
            this.bunifuButtonDepartmentEdit.AllowToggling = false;
            this.bunifuButtonDepartmentEdit.AnimationSpeed = 200;
            this.bunifuButtonDepartmentEdit.AutoGenerateColors = false;
            this.bunifuButtonDepartmentEdit.AutoRoundBorders = false;
            this.bunifuButtonDepartmentEdit.AutoSizeLeftIcon = true;
            this.bunifuButtonDepartmentEdit.AutoSizeRightIcon = true;
            this.bunifuButtonDepartmentEdit.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDepartmentEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDepartmentEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDepartmentEdit.BackgroundImage")));
            this.bunifuButtonDepartmentEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.ButtonText = "     Thay đổi";
            this.bunifuButtonDepartmentEdit.ButtonTextMarginLeft = 0;
            this.bunifuButtonDepartmentEdit.ColorContrastOnClick = 45;
            this.bunifuButtonDepartmentEdit.ColorContrastOnHover = 45;
            this.bunifuButtonDepartmentEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButtonDepartmentEdit.CustomizableEdges = borderEdges5;
            this.bunifuButtonDepartmentEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDepartmentEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonDepartmentEdit.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonDepartmentEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDepartmentEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonDepartmentEdit.IconMarginLeft = 11;
            this.bunifuButtonDepartmentEdit.IconPadding = 10;
            this.bunifuButtonDepartmentEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDepartmentEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonDepartmentEdit.IconSize = 25;
            this.bunifuButtonDepartmentEdit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonDepartmentEdit.IdleBorderRadius = 15;
            this.bunifuButtonDepartmentEdit.IdleBorderThickness = 1;
            this.bunifuButtonDepartmentEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDepartmentEdit.IdleIconLeftImage = null;
            this.bunifuButtonDepartmentEdit.IdleIconRightImage = null;
            this.bunifuButtonDepartmentEdit.IndicateFocus = false;
            this.bunifuButtonDepartmentEdit.Location = new System.Drawing.Point(192, 644);
            this.bunifuButtonDepartmentEdit.Name = "bunifuButtonDepartmentEdit";
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonDepartmentEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentEdit.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentEdit.onHoverState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.onHoverState.BorderThickness = 1;
            this.bunifuButtonDepartmentEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentEdit.onHoverState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.onHoverState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderThickness = 1;
            this.bunifuButtonDepartmentEdit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDepartmentEdit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentEdit.OnIdleState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.OnIdleState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderThickness = 1;
            this.bunifuButtonDepartmentEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentEdit.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.OnPressedState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.Size = new System.Drawing.Size(115, 32);
            this.bunifuButtonDepartmentEdit.TabIndex = 16;
            this.bunifuButtonDepartmentEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonDepartmentEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDepartmentEdit.TextMarginLeft = 0;
            this.bunifuButtonDepartmentEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDepartmentEdit.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Times New Roman", 11F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(617, 100);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(165, 17);
            this.bunifuLabel4.TabIndex = 15;
            this.bunifuLabel4.Text = "Danh sách chuyên ngành:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Times New Roman", 11F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(172, 100);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(108, 17);
            this.bunifuLabel2.TabIndex = 13;
            this.bunifuLabel2.Text = "Danh sách khoa:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDataGridViewMajor
            // 
            this.bunifuDataGridViewMajor.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridViewMajor.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewMajor.BackgroundColor = System.Drawing.Color.LightCyan;
            this.bunifuDataGridViewMajor.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridViewMajor.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewMajor.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewMajor.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridViewMajor.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.Name = null;
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewMajor.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridViewMajor.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewMajor.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewMajor.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridViewMajor.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewMajor.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.Location = new System.Drawing.Point(482, 121);
            this.bunifuDataGridViewMajor.Name = "bunifuDataGridViewMajor";
            this.bunifuDataGridViewMajor.RowHeadersVisible = false;
            this.bunifuDataGridViewMajor.RowTemplate.Height = 40;
            this.bunifuDataGridViewMajor.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewMajor.Size = new System.Drawing.Size(433, 508);
            this.bunifuDataGridViewMajor.TabIndex = 12;
            this.bunifuDataGridViewMajor.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // pictureBox3
            // 
            this.pictureBox3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(69, 644);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(25, 32);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 11;
            this.pictureBox3.TabStop = false;
            // 
            // bunifuButtonDepartmentDelete
            // 
            this.bunifuButtonDepartmentDelete.AllowAnimations = true;
            this.bunifuButtonDepartmentDelete.AllowMouseEffects = true;
            this.bunifuButtonDepartmentDelete.AllowToggling = false;
            this.bunifuButtonDepartmentDelete.AnimationSpeed = 200;
            this.bunifuButtonDepartmentDelete.AutoGenerateColors = false;
            this.bunifuButtonDepartmentDelete.AutoRoundBorders = false;
            this.bunifuButtonDepartmentDelete.AutoSizeLeftIcon = true;
            this.bunifuButtonDepartmentDelete.AutoSizeRightIcon = true;
            this.bunifuButtonDepartmentDelete.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDepartmentDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDepartmentDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDepartmentDelete.BackgroundImage")));
            this.bunifuButtonDepartmentDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.ButtonText = "Xóa";
            this.bunifuButtonDepartmentDelete.ButtonTextMarginLeft = 0;
            this.bunifuButtonDepartmentDelete.ColorContrastOnClick = 45;
            this.bunifuButtonDepartmentDelete.ColorContrastOnHover = 45;
            this.bunifuButtonDepartmentDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButtonDepartmentDelete.CustomizableEdges = borderEdges6;
            this.bunifuButtonDepartmentDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDepartmentDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonDepartmentDelete.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonDepartmentDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDepartmentDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonDepartmentDelete.IconMarginLeft = 11;
            this.bunifuButtonDepartmentDelete.IconPadding = 10;
            this.bunifuButtonDepartmentDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDepartmentDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonDepartmentDelete.IconSize = 25;
            this.bunifuButtonDepartmentDelete.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonDepartmentDelete.IdleBorderRadius = 15;
            this.bunifuButtonDepartmentDelete.IdleBorderThickness = 1;
            this.bunifuButtonDepartmentDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDepartmentDelete.IdleIconLeftImage = null;
            this.bunifuButtonDepartmentDelete.IdleIconRightImage = null;
            this.bunifuButtonDepartmentDelete.IndicateFocus = false;
            this.bunifuButtonDepartmentDelete.Location = new System.Drawing.Point(56, 644);
            this.bunifuButtonDepartmentDelete.Name = "bunifuButtonDepartmentDelete";
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonDepartmentDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentDelete.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentDelete.onHoverState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.onHoverState.BorderThickness = 1;
            this.bunifuButtonDepartmentDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentDelete.onHoverState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.onHoverState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(209)))), ((int)(((byte)(215)))));
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderThickness = 1;
            this.bunifuButtonDepartmentDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(189)))), ((int)(((byte)(175)))));
            this.bunifuButtonDepartmentDelete.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentDelete.OnIdleState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.OnIdleState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderThickness = 1;
            this.bunifuButtonDepartmentDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentDelete.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.OnPressedState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.Size = new System.Drawing.Size(115, 32);
            this.bunifuButtonDepartmentDelete.TabIndex = 10;
            this.bunifuButtonDepartmentDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonDepartmentDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDepartmentDelete.TextMarginLeft = 0;
            this.bunifuButtonDepartmentDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDepartmentDelete.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuDataGridViewDeparment
            // 
            this.bunifuDataGridViewDeparment.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridViewDeparment.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewDeparment.BackgroundColor = System.Drawing.Color.LightCyan;
            this.bunifuDataGridViewDeparment.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridViewDeparment.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewDeparment.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewDeparment.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridViewDeparment.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.Name = null;
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewDeparment.DefaultCellStyle = dataGridViewCellStyle6;
            this.bunifuDataGridViewDeparment.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewDeparment.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridViewDeparment.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridViewDeparment.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewDeparment.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.Location = new System.Drawing.Point(25, 121);
            this.bunifuDataGridViewDeparment.Name = "bunifuDataGridViewDeparment";
            this.bunifuDataGridViewDeparment.RowHeadersVisible = false;
            this.bunifuDataGridViewDeparment.RowTemplate.Height = 40;
            this.bunifuDataGridViewDeparment.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewDeparment.Size = new System.Drawing.Size(433, 508);
            this.bunifuDataGridViewDeparment.TabIndex = 4;
            this.bunifuDataGridViewDeparment.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifubuttonMajorDeleteSearch
            // 
            this.bunifubuttonMajorDeleteSearch.ActiveBorderThickness = 1;
            this.bunifubuttonMajorDeleteSearch.ActiveCornerRadius = 20;
            this.bunifubuttonMajorDeleteSearch.ActiveFillColor = System.Drawing.Color.SeaGreen;
            this.bunifubuttonMajorDeleteSearch.ActiveForecolor = System.Drawing.Color.White;
            this.bunifubuttonMajorDeleteSearch.ActiveLineColor = System.Drawing.Color.SeaGreen;
            this.bunifubuttonMajorDeleteSearch.BackColor = System.Drawing.Color.Transparent;
            this.bunifubuttonMajorDeleteSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifubuttonMajorDeleteSearch.BackgroundImage")));
            this.bunifubuttonMajorDeleteSearch.ButtonText = "Xóa tìm kiếm";
            this.bunifubuttonMajorDeleteSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifubuttonMajorDeleteSearch.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifubuttonMajorDeleteSearch.ForeColor = System.Drawing.Color.Maroon;
            this.bunifubuttonMajorDeleteSearch.IdleBorderThickness = 1;
            this.bunifubuttonMajorDeleteSearch.IdleCornerRadius = 20;
            this.bunifubuttonMajorDeleteSearch.IdleFillColor = System.Drawing.Color.White;
            this.bunifubuttonMajorDeleteSearch.IdleForecolor = System.Drawing.Color.SeaGreen;
            this.bunifubuttonMajorDeleteSearch.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifubuttonMajorDeleteSearch.Location = new System.Drawing.Point(685, 29);
            this.bunifubuttonMajorDeleteSearch.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifubuttonMajorDeleteSearch.Name = "bunifubuttonMajorDeleteSearch";
            this.bunifubuttonMajorDeleteSearch.Size = new System.Drawing.Size(111, 34);
            this.bunifubuttonMajorDeleteSearch.TabIndex = 3;
            this.bunifubuttonMajorDeleteSearch.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Times New Roman", 11F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(99, 41);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(72, 17);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Tìm kiếm :";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBoxMajorSearch
            // 
            this.bunifuTextBoxMajorSearch.AcceptsReturn = false;
            this.bunifuTextBoxMajorSearch.AcceptsTab = false;
            this.bunifuTextBoxMajorSearch.AnimationSpeed = 200;
            this.bunifuTextBoxMajorSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxMajorSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxMajorSearch.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxMajorSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxMajorSearch.BackgroundImage")));
            this.bunifuTextBoxMajorSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxMajorSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxMajorSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxMajorSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxMajorSearch.BorderRadius = 1;
            this.bunifuTextBoxMajorSearch.BorderThickness = 1;
            this.bunifuTextBoxMajorSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxMajorSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMajorSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxMajorSearch.DefaultText = "";
            this.bunifuTextBoxMajorSearch.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxMajorSearch.HideSelection = true;
            this.bunifuTextBoxMajorSearch.IconLeft = null;
            this.bunifuTextBoxMajorSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMajorSearch.IconPadding = 10;
            this.bunifuTextBoxMajorSearch.IconRight = null;
            this.bunifuTextBoxMajorSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMajorSearch.Lines = new string[0];
            this.bunifuTextBoxMajorSearch.Location = new System.Drawing.Point(192, 33);
            this.bunifuTextBoxMajorSearch.MaxLength = 32767;
            this.bunifuTextBoxMajorSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxMajorSearch.Modified = false;
            this.bunifuTextBoxMajorSearch.Multiline = false;
            this.bunifuTextBoxMajorSearch.Name = "bunifuTextBoxMajorSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMajorSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxMajorSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMajorSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMajorSearch.OnIdleState = stateProperties4;
            this.bunifuTextBoxMajorSearch.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxMajorSearch.PasswordChar = '\0';
            this.bunifuTextBoxMajorSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxMajorSearch.PlaceholderText = "Enter text";
            this.bunifuTextBoxMajorSearch.ReadOnly = false;
            this.bunifuTextBoxMajorSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxMajorSearch.SelectedText = "";
            this.bunifuTextBoxMajorSearch.SelectionLength = 0;
            this.bunifuTextBoxMajorSearch.SelectionStart = 0;
            this.bunifuTextBoxMajorSearch.ShortcutsEnabled = true;
            this.bunifuTextBoxMajorSearch.Size = new System.Drawing.Size(475, 30);
            this.bunifuTextBoxMajorSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxMajorSearch.TabIndex = 1;
            this.bunifuTextBoxMajorSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxMajorSearch.TextMarginBottom = 0;
            this.bunifuTextBoxMajorSearch.TextMarginLeft = 3;
            this.bunifuTextBoxMajorSearch.TextMarginTop = 0;
            this.bunifuTextBoxMajorSearch.TextPlaceholder = "Enter text";
            this.bunifuTextBoxMajorSearch.UseSystemPasswordChar = false;
            this.bunifuTextBoxMajorSearch.WordWrap = true;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 100;
            this.bunifuElipse1.TargetControl = this;
            // 
            // FormMainDeptMajor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Name = "FormMainDeptMajor";
            this.Size = new System.Drawing.Size(940, 695);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewMajor)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewDeparment)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private System.Windows.Forms.PictureBox pictureBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonDepartmentDelete;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewDeparment;
        private Bunifu.Framework.UI.BunifuThinButton2 bunifubuttonMajorDeleteSearch;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxMajorSearch;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonDepartmentEdit;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewMajor;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMajorAdd;
        private System.Windows.Forms.PictureBox pictureBox6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMajorEdit;
        private System.Windows.Forms.PictureBox pictureBox5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMajorDelete;
        private System.Windows.Forms.PictureBox pictureBox4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonDeparmentAdd;
    }
}
